/// <reference types="next" />
/// <reference types="next/image-types/global" />
/// <reference types="@nx/next/typings/style.d.ts" />
// Next's own types live here too, so typecheck works on a fresh checkout:
// next-env.d.ts is generated by next dev/build and not committed.
/* eslint-disable @typescript-eslint/no-explicit-any */
declare module '*.svg' {
  const content: any;
  export const ReactComponent: any;
  export default content;
}
