version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      nx:
        patterns: ['nx', '@nx/*']
      nestjs:
        patterns: ['@nestjs/*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /tools/docker
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directories:
      - /infra/terraform/live/dev/*
    schedule:
      interval: weekly
